version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: v1-dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Installing dependencies
          command: |
            sudo pip install poetry
            poetry install

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/home/circleci/.cache/pypoetry/virtualenvs"
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      # Run tests
      - run:
          name: Run Pytest
          command: |
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs/*" -m pytest --junitxml=test-results/pytest/results.xml

      - run:
          name: Run linting and coverage
          command: |
            poetry run flake8 .
            poetry run black --check --diff src
            poetry run coverage report

      - store_test_results:
          path: test-results
