version: '3.6'
services:

  backend:
    image: backend:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: Dev
    container_name: backend02
    env_file:
      - .env
    volumes:
      - ../src:/src
    ports:
      - 8000:8000
    depends_on:
      - db


  ngrok-pyback:
    image: wernight/ngrok:latest
    env_file:
      - .ngrok.env
    environment:
      - NGROK_PORT=backend:8000
      - NGROK_SUBDOMAIN=pyback
    ports:
      - 4040:4040

  db:
    image: postgres:10.1-alpine
    container_name: pg01
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: