version: '3.6'
services:

  backend:
    image: back-end:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: Staging
    container_name: backend02
    env_file:
      - .env
    ports:
      - 8000:8000

  pybot:
    image: pybot:latest
    container_name: pybot01
    env_file:
      - pybot.env
    ports:
      - 5000:5000